This is makeindex, version 2.15 [MiKTeX 2.9.7140 64-bit] (kpathsea + Thai support).
Scanning style file ./PRO_Helfenbein_Zoll_documentation.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file PRO_Helfenbein_Zoll_documentation.acn....done (2 entries accepted, 0 rejected).
Sorting entries....done (2 comparisons).
Generating output file PRO_Helfenbein_Zoll_documentation.acr....done (6 lines written, 0 warnings).
Output written in PRO_Helfenbein_Zoll_documentation.acr.
Transcript written in PRO_Helfenbein_Zoll_documentation.alg.
